#!/bin/sh

### BEGIN ###
# Author: idevz
# Since: 2018/03/12
# Description:       Manage a motan openresty dependences
### END ###

DAPP_NAME=motan-demo
SRC_ROOT=`realpath ./`
DAPP_ROOT=${SRC_ROOT}/app

APP_NAME=${APP_NAME=$DAPP_NAME}
APP_ROOT=${APP_ROOT=$DAPP_ROOT}

DEMO_APP_SRC=${SRC_ROOT}/build/app
DEMO_APP_GIT="https://github.com/motan-ecosystem/motan-openresty-demo.git"

mkdir -p $DEMO_APP_SRC ${APP_ROOT}/${APP_NAME}
cd $DEMO_APP_SRC
git clone $DEMO_APP_GIT $APP_NAME
cp -fR ${DEMO_APP_SRC}/${APP_NAME}/* ${APP_ROOT}/${APP_NAME}/
