#!/bin/sh

### BEGIN ###
# Author: idevz
# Since: 2018/03/12
# Description:       Manage a motan openresty dependences
### END ###

DEPENDENCES='https://github.com/pintsized/lua-resty-http/archive/v0.12.tar.gz https://github.com/idevz/lua-resty-timer.git https://github.com/hamishforbes/lua-resty-consul/archive/v0.2.tar.gz'
SRC_ROOT=$(realpath ./)
REQUIRE=${SRC_ROOT}/build/require

mkdir -p $REQUIRE/{src,resty}

for dep in ${DEPENDENCES}
do
    if echo $dep| grep -q "\.git";then
        cd $REQUIRE/src;
        git clone $dep;
        cp -fR lua-resty-timer/lib/resty/* $REQUIRE/resty/
    else
        cd $REQUIRE/src
        FILE_NAME=$(echo $dep | sed 's/.*\(lua-resty[^\/]*\)\/.*/\1/g')
        wget --no-check-certificate $dep -O $FILE_NAME
        tar zxf $FILE_NAME
        cp -fR $FILE_NAME*/lib/resty/* $REQUIRE/resty/
    fi
done